packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@autonomos/cli@0.3.4'
  - '@autonomos/core@0.3.2'
  - '@turbo/darwin-64@2.11.4'
  - '@turbo/darwin-arm64@2.11.4'
  - '@turbo/linux-64@2.11.4'
  - '@turbo/linux-arm64@2.11.4'
  - '@turbo/windows-64@2.11.4'
  - '@turbo/windows-arm64@2.11.4'
  - eslint-plugin-turbo@2.11.4
  - turbo@2.11.4
